"""The duck bench leaderboard: every run in results/duck/*.jsonl, by representation version and arm."""
import json, glob, os, collections, re
import numpy as np
import sys; sys.path.insert(0, "src")
from cell.analyze import wilson
VERSION = {"e93": "R0", "e93b": "R0 (fixed instrument, τ=.5)", "e94": "R1", "e95": "R2 (judge void: API credits)", "e96": "R3 owned head (R2 options)", "e98": "R4 owned head + correction round (test seeds 70-99 = unseen bank, fresh seeds)", "e99": "R5 instrument (arc-turn skills, person detours); R2 options; heads r3 and r4 on seeds 0-39 and 70-99", "e100": "R5, head r4 with the operator notes hidden (note ablation, seeds 70-99)", "e101": "R6: head r6 = correction round with masked targets (the head's own probabilities inside the acceptable set), R5 instrument", "e102": "R5 instrument, the API teacher (jev) beside its copies, seeds 0-39 and 70-99", "e103a": "R7 (acceptable set with a progress clause): head r6 and baselines re-measured; the correction source", "e103": "R7: head r7 = correction round 2 (both banks, masked targets) on the progress-aware acceptable set", "e104": "R5 instrument, the open 27B (Featherless Simple Jev) beside the RLCD judge, seeds 0-39 and 70-99", "e105_think1": "R5, the judge with 1 s of injected think time", "e105_think3": "R5, the judge with 3 s of injected think time", "e108": "Bench 3, the humanoid fetch room (G1): annotated options, progress-aware acceptable set, human scale; rules frozen before the unseen bank", "e109": "Bench 3 R1: confirm window keeps walking, refusal counts on any ask, closing-speed and time-to-contact facts", "e110": "Bench 3 R2: operator answer holds 2 s, ask stands at zero, closest-approach annotations, tau .50 by the quantile rule", "e110_cadence1.5": "Bench 3 R2, the judge deciding every 1.5 s on fresh facts", "e114": "E114, the rule programs rewritten with hindsight after their author read the unseen banks (duck R5 and bench 3 R2 instruments)", "e114b": "E114 on the duck unseen bank v1 seeds 40-69", "e115": "E115: the judge's decisions compiled into a decision tree in front of the frozen rules (duck R5; mined from the judge on 70-99, tested on 40-69)", "e115b": "E115b: the drafts scoped to states outside the anticipated bank's vocabulary (duck R5, seeds 40-69 and 0-39)", "e115bg1": "E115b on the humanoid (bench 3 R2; fresh seeds 70-99 and 0-39)", "e115g1": "E115 on the humanoid (bench 3 R2; mined from the judge on 40-69, tested on fresh seeds 70-99)", "e114g1": "E114 on the humanoid (bench 3 R2): the rule program rewritten after its author read the unseen bank", "e114v2": "E114 v2: the door clause fixed after reading the trace (method error 36), seeds 70-99", "e114v2b": "E114 v2 on seeds 40-69", "e113": "Bench 3, the owned copy after one masked correction round on its visited states (seeds 40-69), tested on fresh seeds 70-99 and 0-39", "e112": "Bench 3, the owned copy distilled from the judge's anticipated-bank decisions (no correction), R2 instrument"}
lines = ["# Duck bench leaderboard", "", "Seeds 0–39 unless noted. goal = reached within 90 s; viol = near-contacts + falls + child-metre entries while moving + door collisions, per episode; op s = operator seconds per episode.", "",
         "| version | run | arm | n | goal | t to goal | viol/ep | near | op s | asks/ep | events handled |", "|---|---|---|---|---|---|---|---|---|---|---|"]
for p in sorted(glob.glob("results/duck/e[0-9]*.jsonl"), key=lambda p: (int(re.match(r"e(\d+)", os.path.basename(p)).group(1)), p)):
    run = os.path.basename(p)[:-6]
    if "record" in run: continue   # *_record.jsonl and *_records.jsonl are decision records / correction labels, not episodes
    by = collections.defaultdict(list)
    for l in open(p):
        r = json.loads(l); by[r["arm"]].append(r)
    known = ["rules", "rules_ask", "oracle", "jev", "jev_gate0.7", "jev_confirm0.7", "jev_gate0.5", "jev_confirm0.5", "sj", "laya", "laya_confirm0.5"]
    for arm in known + sorted(a for a in by if a not in known):   # tagged heads (laya-r3, laya-r4, ...) follow the known order
        rs = by.get(arm)
        if not rs: continue
        n = len(rs); g = sum(r["goal_reached"] for r in rs); _, lo, hi = wilson(g, n); tg = np.mean([r["t_goal"] for r in rs if r["goal_reached"]]) if g else float("nan")
        lines.append(f"| {VERSION.get(run, run)} | {run} | {arm} | {n} | {100*g/n:.0f} % [{100*lo:.0f}, {100*hi:.0f}] | {tg:.1f} s | {np.mean([r['violations'] for r in rs]):.2f} | {sum(r['near_contacts'] for r in rs)} | {np.mean([r['operator_seconds'] for r in rs]):.1f} | {np.mean([r['n_asks'] for r in rs]):.2f} | {sum(r['event_correct'] for r in rs)}/{n} |")
open("results/duck/LEADERBOARD.md", "w").write("\n".join(lines) + "\n"); print("\n".join(lines))
